# Generated by Django 3.0.1 on 2020-09-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('store', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('types', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('date', models.TextField()),
                ('weekly_sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_tienda_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Tiendas')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('temperature', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('md1', models.CharField(max_length=50)),
                ('md2', models.CharField(max_length=50)),
                ('md3', models.CharField(max_length=50)),
                ('md4', models.CharField(max_length=50)),
                ('md5', models.CharField(max_length=50)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unenemplyment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_holiday', models.BooleanField(default=False)),
                ('id_tienda_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Tiendas')),
            ],
        ),
    ]
