# Generated by Django 3.0.1 on 2020-09-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='isholiday',
            field=models.CharField(default='FALSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='is_holiday',
            field=models.CharField(max_length=50),
        ),
    ]
