# Generated by Django 3.0.1 on 2020-09-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200923_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas22',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('field_store', models.IntegerField(blank=True, db_column='\ufeffStore', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('temperature', models.FloatField(blank=True, db_column='Temperature', null=True)),
                ('fuel_price', models.FloatField(blank=True, db_column='Fuel_Price', null=True)),
                ('markdown1', models.TextField(blank=True, db_column='MarkDown1', null=True)),
                ('markdown2', models.TextField(blank=True, db_column='MarkDown2', null=True)),
                ('markdown3', models.TextField(blank=True, db_column='MarkDown3', null=True)),
                ('markdown4', models.TextField(blank=True, db_column='MarkDown4', null=True)),
                ('markdown5', models.TextField(blank=True, db_column='MarkDown5', null=True)),
                ('cpi', models.FloatField(blank=True, db_column='CPI', null=True)),
                ('unemployment', models.FloatField(blank=True, db_column='Unemployment', null=True)),
                ('isholiday', models.TextField(blank=True, db_column='IsHoliday', null=True)),
            ],
            options={
                'db_table': 'caracteristicas22',
                'managed': False,
            },
        ),
    ]
