# Generated by Django 3.0.1 on 2020-09-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_caracteristicas22'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('temperature', models.FloatField(blank=True, db_column='Temperature', null=True)),
                ('fuel_price', models.FloatField(blank=True, db_column='Fuel_Price', null=True)),
                ('markdown1', models.FloatField(blank=True, db_column='MarkDown1', null=True)),
                ('markdown2', models.FloatField(blank=True, db_column='MarkDown2', null=True)),
                ('markdown3', models.FloatField(blank=True, db_column='MarkDown3', null=True)),
                ('markdown4', models.FloatField(blank=True, db_column='MarkDown4', null=True)),
                ('markdown5', models.FloatField(blank=True, db_column='MarkDown5', null=True)),
                ('cpi', models.FloatField(blank=True, db_column='CPI', null=True)),
                ('unemployment', models.FloatField(blank=True, db_column='Unemployment', null=True)),
                ('isholiday', models.TextField(blank=True, db_column='IsHoliday', null=True)),
                ('id_tienda_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Tiendas')),
            ],
        ),
    ]
