# Generated by Django 3.0.1 on 2020-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200924_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(blank=True, null=True)),
                ('Dept', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Weekly_Sales', models.FloatField(blank=True, null=True)),
                ('IsHoliday', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
